### ISSUE TITLE
`StoryMetadata` vs `StoryData`

### ISSUE THREAD

**Issue by ChapelR** [videlais/extwee#1]
The twee3 spec calls the metadata passage `StoryData`. Extwee seems to be looking for a passage called `StoryMetadata` from what I can see in the source code. I have *not* actually tried out Extwee yet, but I plan to, so I don't want to give the impression I did.

**Comment by videlais** [comment]
Thanks for catching that! That typo was a leftover from a previous version of the specification. I've updated the file and will produce some new builds as soon as I can.
